name: Build and deploy 
run-name: ${{ github.actor }} is testing code coverage summary 🚀

on:
  push:
env:
  GITHUB_ORGANIZATION: jpontdia
  GIST_ID: ef8cdef1ff940eac4d8716f6361d2363
jobs:
  Mulesoft:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
  
    steps:

      - name: Get the source code
        uses: actions/checkout@v3

      - name: Summary - Unit test cases
        # if:  ${{ false }}
        uses: jpontdia/devops-pipelines/packages/summary-testcases@main
        with:
          gist-token: ${{ secrets.GIST_TOKEN}}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.GIST_ID }}
          debug: "true"

      - name: Summary - Code coverage
        # if:  ${{ false }}
        uses: jpontdia/devops-pipelines/packages/summary-codecoverage@main
        with:
          gist-token: ${{ secrets.GIST_TOKEN}}
          github-organization: ${{ env.GITHUB_ORGANIZATION }}
          badge-gist-id: ${{ env.GIST_ID }}
          debug: true

      - name: Summary - Add code coverage
        if:  ${{ false }}
        run: |
          temporal=""
          line=0
          trigger=0
          while IFS= read -r p; do
          
            if [[ "$p" == *"<div class=\"col-md-8 col-md-offset-2\">"* ]]; then
              echo "Summary starts at line: $line"
              ((line=line+1))
              trigger=1
              continue
            fi

            if [[ $trigger == 1 ]]; then
              # echo "${p:0:6}"
              echo "$p"
              if [[ "${p:0:6}" == "</div>" ]]; then
                echo "Exit condition at line: $line"
                break
              else
                temporal+=$p
              fi
            fi

            ((line=line+1))
          done < target/site/munit/coverage/summary.html

          # Remove html tag: <a>
          temporal=$(sed -e 's/<\/a[^>]*>//g' <<<"$temporal")
          temporal=$(sed -e 's/<a[^>]*>//g' <<<"$temporal")

          # Add job summary 
          echo "<div>" >> $GITHUB_STEP_SUMMARY
          echo "$temporal" >> $GITHUB_STEP_SUMMARY
          echo "</div>" >> $GITHUB_STEP_SUMMARY
